-- Migration sugerida: criar tabela oficial para plano/acesso dos clientes
-- Revise antes de rodar em produção.

create table if not exists public.client_access (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  plan text not null check (plan in ('free', 'premium')),
  status text not null default 'active',
  source_roles text,
  source_plan_id uuid null,
  migrated_from text not null default 'clientes-2026-07-01.json',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  constraint client_access_user_id_unique unique (user_id)
);

-- Inserções normalizadas a partir do JSON analisado:
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('9d0a960a-f010-400c-b786-b479776e7362', 'free', 'active', 'ROLE_USER_FREE', null) on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('463803b3-d55b-49e9-a248-df56e6a04ea3', 'free', 'active', 'ROLE_USER_FREE', null) on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('f2d4cede-7ec8-44a2-95f6-2e2eb9775983', 'free', 'active', 'ROLE_USER_FREE', null) on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('e44b0902-24a6-4cd0-a9ab-ea4bb28caf45', 'free', 'active', 'ROLE_USER_FREE', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('d300e558-63c3-45fd-8a9e-cd211c3aa24c', 'free', 'active', 'ROLE_USER_FREE', null) on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('7dca8f48-23cc-42ec-95a4-732549e7df3d', 'free', 'active', 'ROLE_USER_FREE', null) on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('a28844c4-d2e9-4477-954a-ba74b896d81c', 'free', 'active', 'ROLE_USER_FREE', null) on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('a9131297-7c01-405b-8e7f-ccd68260693f', 'free', 'active', 'ROLE_USER_FREE', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('998a35d5-d5e2-43d7-b01b-f0660dbd0d66', 'premium', 'active', 'ROLE_USER_FREE, ROLE_USER', '98e82600-8a48-4107-a2ec-eac4973f30a8') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('32ea7a4a-c563-44ea-aeef-21c69e91572e', 'premium', 'active', 'ROLE_USER_FREE, ROLE_USER', '98e82600-8a48-4107-a2ec-eac4973f30a8') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('c3eeecf3-d458-4e86-9690-b11e322d50c2', 'premium', 'active', 'ROLE_USER_FREE, ROLE_USER', '98e82600-8a48-4107-a2ec-eac4973f30a8') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('0736fefa-51e8-4d71-b160-95da8c3affb2', 'free', 'active', 'ROLE_USER_FREE', null) on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('4024ea43-da67-4670-8aa1-6dd4ff5a68cd', 'free', 'active', 'ROLE_USER_FREE', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('95051cd7-dbb4-4844-bc44-bb0eae27679f', 'free', 'active', 'ROLE_USER_FREE', null) on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('c6b4e61f-770d-4a12-91cc-192bcd54101d', 'free', 'active', 'ROLE_USER_FREE', null) on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('ca1c7079-a6e8-471b-bef6-85444cd08f57', 'free', 'active', 'ROLE_USER_FREE', null) on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('4992ef52-00e4-44a1-bf53-1740a557fa60', 'free', 'active', 'ROLE_USER_FREE', null) on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('dc796fd5-cf51-4200-a316-84aafa18bfb7', 'free', 'active', 'ROLE_USER_FREE', null) on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('31591e38-a6b7-4daf-aa24-eb5b29b04c5a', 'free', 'active', 'ROLE_USER_FREE', null) on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('2860f077-d9cd-472b-8fd6-d02c882fab68', 'free', 'active', 'ROLE_USER_FREE', null) on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('f676819d-d6e0-4f81-949e-04e1263e9e63', 'free', 'active', 'ROLE_USER_FREE', null) on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('4a431c13-813d-4c1a-9951-1590f12489d0', 'free', 'active', 'ROLE_USER_FREE', null) on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('5b9032aa-e191-4438-af02-2d67b43422a5', 'free', 'active', 'ROLE_USER_FREE', null) on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('029b008b-03da-4bbe-8304-4c6c255f72b6', 'free', 'active', 'ROLE_USER_FREE', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('2d5ff90e-d514-4249-b996-d7a0e7615ace', 'free', 'active', 'ROLE_USER_FREE', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('76f884e7-94b4-445b-a949-2a736623b49f', 'free', 'active', 'ROLE_USER_FREE', null) on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('a8b24c0c-e2d4-44ce-83cd-4c80151f8ca7', 'free', 'active', 'ROLE_USER_FREE', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('0a7ff2ca-eb39-4456-9289-9bf62e4809f5', 'free', 'active', 'ROLE_USER_FREE', null) on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('2838214d-7e5d-450a-985f-6cd1752fe5ab', 'free', 'active', 'ROLE_USER_FREE', null) on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('aa202a45-e998-41e4-8414-fd70238b2c36', 'free', 'active', 'ROLE_USER_FREE', null) on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('83e7b8ab-4025-40e6-a011-f00481049264', 'free', 'active', 'ROLE_USER_FREE', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('c622f17a-953d-4104-80c5-6427a8fd18bd', 'free', 'active', 'ROLE_USER_FREE', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('af1c94f5-9e7d-45d1-9e05-b005a7156041', 'free', 'active', 'ROLE_USER_FREE', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('9836303b-e89c-4aa6-8706-ca7dd9c94c76', 'free', 'active', 'ROLE_USER_FREE', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('fbb5217d-59d5-4f35-84ba-9c4e7fb2a257', 'premium', 'active', 'ROLE_USER_FREE, ROLE_USER', '98e82600-8a48-4107-a2ec-eac4973f30a8') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('f04595cd-2ace-4905-a316-0ddeef57e18b', 'free', 'active', 'ROLE_USER_FREE', '98e82600-8a48-4107-a2ec-eac4973f30a8') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('d150b3d6-21d2-42d2-ba48-2f8e46b9f2cf', 'free', 'active', 'ROLE_USER_FREE', '98e82600-8a48-4107-a2ec-eac4973f30a8') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('cd8f12ae-61d8-4d06-bfbb-d08e967ee57e', 'free', 'active', 'ROLE_USER_FREE', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('0b386194-a1e8-4ddb-8368-b38f22ff4931', 'premium', 'active', 'ROLE_USER, ROLE_USER_FREE', '98e82600-8a48-4107-a2ec-eac4973f30a8') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('a469bd52-a6e5-4f48-ad65-ddacaaf4b5e6', 'free', 'active', 'ROLE_USER_FREE', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('c708933a-87d5-4b09-bfac-8ab5abc25e78', 'premium', 'active', 'ROLE_USER', '98e82600-8a48-4107-a2ec-eac4973f30a8') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('7a22db16-200c-4569-bb34-e614cc92d0e8', 'free', 'active', 'ROLE_USER_FREE', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('2925a817-9ac9-4806-b3cf-f979394d3b1d', 'free', 'active', 'ROLE_USER_FREE', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('5937319b-7455-4edc-ab2e-bc25150504a8', 'free', 'active', 'ROLE_USER_FREE', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('e4d91802-4968-4ea0-8fd7-770016c65505', 'free', 'active', 'ROLE_USER_FREE', '98e82600-8a48-4107-a2ec-eac4973f30a8') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('78adb59d-ce19-4e44-b655-ac43a6c21885', 'free', 'active', 'ROLE_USER_FREE', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('c1c2f0bf-fb9e-4654-9b57-eb2d1fbf4aac', 'free', 'active', 'ROLE_USER_FREE', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('78e063f9-0e57-4800-b11f-1781143f7e68', 'free', 'active', 'ROLE_USER_FREE', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('c36e1576-cdd5-48d7-9eca-2d6ff644f367', 'free', 'active', 'ROLE_USER_FREE', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('34ae0ce1-beb4-4cc6-91cc-b81c62e593f2', 'free', 'active', 'ROLE_USER_FREE', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('ce2255aa-0f46-4895-bb8a-699a69dafd51', 'free', 'active', 'ROLE_USER_FREE', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('ccdc1bc2-729c-440b-adc1-ac05f364cec5', 'free', 'active', 'ROLE_USER_FREE', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('570aeff9-88b5-4493-bf35-aa5e719c0f1c', 'free', 'active', 'ROLE_USER_FREE', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('2ecf72dc-8c64-4aae-97e9-6625c049e973', 'free', 'active', 'ROLE_USER_FREE', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('450bf70d-353a-47d4-b3c3-91579e3e88e7', 'free', 'active', 'ROLE_USER_FREE', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('e7da8579-b983-4145-b1e7-e7d822ca1bdb', 'premium', 'active', 'ROLE_USER, ROLE_USER_FREE', '98e82600-8a48-4107-a2ec-eac4973f30a8') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('c48b4616-1e36-4c52-a088-85a69181142d', 'free', 'active', 'ROLE_USER_FREE', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('42db85ac-ac4e-4942-8f08-28bc15433233', 'free', 'active', 'ROLE_USER_FREE', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('e2ab3b19-6efa-4580-a562-df6efb72a654', 'free', 'active', 'ROLE_USER_FREE', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('b40e584c-53cc-4e82-a85d-b15d05df2bd7', 'free', 'active', 'ROLE_USER_FREE', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('523cf486-828c-498e-9c41-84559a7dbc60', 'free', 'active', 'ROLE_USER_FREE', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('f475a2aa-139d-4b73-9843-8b730009d797', 'premium', 'active', 'ROLE_USER', '98e82600-8a48-4107-a2ec-eac4973f30a8') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('1c2a1d56-5542-4e49-b555-fe14a114e8ae', 'premium', 'active', 'ROLE_USER', '98e82600-8a48-4107-a2ec-eac4973f30a8') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('55f0b1ed-f595-40ad-816c-e15792d361ce', 'free', 'active', 'user, ROLE_USER_FREE', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('cd0396c7-49e4-4217-98a8-37662365f0b9', 'premium', 'active', 'user, ROLE_USER', '98e82600-8a48-4107-a2ec-eac4973f30a8') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('5a3ddb4d-6c85-47ff-8436-bac3770d0a8b', 'free', 'active', 'user, ROLE_USER_FREE', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('569e6962-f214-42f7-9d66-e5e54813a7bd', 'free', 'active', 'user, ROLE_USER_FREE', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('817280b7-9a9d-4095-a911-f78057cfb500', 'free', 'active', 'user, ROLE_USER_FREE', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('fbdfeb84-202d-410e-b5d9-2a8a4a88f64f', 'free', 'active', 'user, ROLE_USER_FREE', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('86489170-0235-4736-aef1-e222e5304e2d', 'free', 'active', 'user, ROLE_USER_FREE', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('8231abc7-e24e-4a26-a920-27b34b435b28', 'free', 'active', 'user, ROLE_USER_FREE', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('d80d4d50-c0a9-421e-9f8f-06a02bff04e8', 'free', 'active', 'user', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('fdaf0cb5-8edc-4d05-84ff-61c1adbaae77', 'free', 'active', 'user', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('581aad4d-0481-4678-baf3-d83afd1a2a40', 'free', 'active', 'user', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('c12107c6-b10e-46f9-bf45-aa1855516e58', 'free', 'active', 'user', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('d8d6eb3b-1edc-4ef5-baf0-c1a3db498026', 'free', 'active', 'user', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('e9edc843-57c5-45ef-9481-d163dbdc98ba', 'free', 'active', 'user, ROLE_USER_FREE', '98e82600-8a48-4107-a2ec-eac4973f30a8') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('4915f85c-91d7-431d-b1a3-b1b2f3d0b2d5', 'premium', 'active', 'ROLE_USER, user', '98e82600-8a48-4107-a2ec-eac4973f30a8') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('1e2d73cd-2457-4e4e-b318-ef91040208eb', 'free', 'active', 'user', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('a1f3db26-1c5a-481f-b70a-ff1edfa82766', 'free', 'active', 'user', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('425ff126-f4b3-4d77-b9a0-5e5903fb739e', 'free', 'active', 'user', '196bdb78-bcb7-4396-ab3c-fbeaa8815568') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('4811aa8f-96eb-4ff4-b235-b2840190dcf3', 'premium', 'active', 'user, ROLE_USER', '98e82600-8a48-4107-a2ec-eac4973f30a8') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();
insert into public.client_access (user_id, plan, status, source_roles, source_plan_id) values ('400b2349-f530-41ce-847f-c45d08f31538', 'free', 'active', 'user', '98e82600-8a48-4107-a2ec-eac4973f30a8') on conflict (user_id) do update set plan = excluded.plan, status = excluded.status, source_roles = excluded.source_roles, source_plan_id = excluded.source_plan_id, updated_at = now();